name: Deploy to Hugging Face
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Push to Hugging Face
        uses: huggingface/huggingface_hub@main
        with:
          huggingface_token: ${{ secrets.HF_TOKEN }}
          repo_id: "ramashishpanchal/hf-space"
          path: "."
          commit_message: "GitHub Actions auto-deploy"